### PR TITLE
Adriancast homepage

### PR DESCRIPTION
**Pull request by adriancast**
This is my proposal. 
IMG2

Hover:

IMG2

Small screen size:
IMG3

Mobile size (iphone 6):
IMG4

I changed a funcion called 'sfwd_get_home_blog()'. That function was in plugins/semperpluginstore/theme_interface.php/ . I moved it to the function file in the theme. I also rename it to sfwd_get_home_blog_section()

### CODE REVIEW

**Comment by wpsmort** [comment]
Ok, thanks @adriancast.  I asked because that's not what I was seeing when I installed the code you sent.  Can you send me the changes you made to the semperpluginstore plugin.

**Comment by michaeltorbert** [comment]
@wpsmort @adriancast My advice would be to make a branch in the semperpluginstore plugin repo for any code changes.

**Comment by wpsmort** [comment]
@adriancast I have created a branch off our development branch here - https://github.com/semperfiwebdesign/semperpluginstore/tree/adriancastellanos

**Comment by adriancast** [comment]
I will check it tonight. Can you send me photos of how it looks please?

**Comment by wpsmort** [comment]
Here's what I see:

screen-capture

**Comment by adriancast** [comment]
I can't access to the semperpluginstore repo. It shouldn't be a problem of the plugin because I don't call it on that section of the blog. I took the function that was using that section previously and I moved to the functions file in the child theme. 

Could you try it again disabling the cache of the browser?

Maybe I am modifying the wrong files. I am modifying the files in the following path:
/wp-content/themes/semperpluginstheme/

**Pull request closed without merging**
